[package]
name = "anubis_notary_oracle"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.0"
openzeppelin_merkle_tree = "0.20.0"

[dev-dependencies]
cairo_test = "2.9.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
